[package]
name = "irontile-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Bar and launcher surfaces for irontile"

[[bin]]
name = "irontile-bar"
path = "src/bin/irontile-bar.rs"

[dependencies]
irontile-power.workspace = true
irontile-ipc.workspace = true
serde.workspace = true
toml.workspace = true
tiny-skia.workspace = true
resvg.workspace = true
usvg.workspace = true
cosmic-text.workspace = true
chrono.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-protocols-wlr.workspace = true
rustix.workspace = true
libpulse-binding.workspace = true
zbus.workspace = true

[lints]
workspace = true
